/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Prediction = IDL.Record({
  'id' : IDL.Nat,
  'prediction' : IDL.Text,
  'homeTeam' : IDL.Text,
  'odds' : IDL.Float64,
  'league' : IDL.Text,
  'awayTeam' : IDL.Text,
  'confidence' : IDL.Nat,
  'analysis' : IDL.Text,
  'matchDate' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addPredictionAsAdmin' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deletePredictionAsAdmin' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'fetchFootballMatches' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchMatchesByCompetition' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getPredictions' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
  'isAdminAuthenticated' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'seedInitialData' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePredictionAsAdmin' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Prediction = IDL.Record({
    'id' : IDL.Nat,
    'prediction' : IDL.Text,
    'homeTeam' : IDL.Text,
    'odds' : IDL.Float64,
    'league' : IDL.Text,
    'awayTeam' : IDL.Text,
    'confidence' : IDL.Nat,
    'analysis' : IDL.Text,
    'matchDate' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addPredictionAsAdmin' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deletePredictionAsAdmin' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'fetchFootballMatches' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchMatchesByCompetition' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getPredictions' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
    'isAdminAuthenticated' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'seedInitialData' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePredictionAsAdmin' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };