/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Prediction {
  'id' : bigint,
  'prediction' : string,
  'homeTeam' : string,
  'odds' : number,
  'league' : string,
  'awayTeam' : string,
  'confidence' : bigint,
  'analysis' : string,
  'matchDate' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addPredictionAsAdmin' : ActorMethod<
    [string, string, string, string, string, string, number, bigint, string],
    [] | [bigint]
  >,
  'adminLogin' : ActorMethod<[string], [] | [string]>,
  'adminLogout' : ActorMethod<[string], boolean>,
  'deletePredictionAsAdmin' : ActorMethod<[string, bigint], boolean>,
  /**
   * / Fetches only Premier League matches.
   */
  'fetchFootballMatches' : ActorMethod<[string], string>,
  /**
   * / Fetch Matches by Competition Code
   * /
   * / competitionCode examples:
   * / "PL" (Premier League), "CL" (Champions League), "PD" (La Liga),
   * / "BL1" (Bundesliga), "SA" (Serie A), "FL1" (Ligue 1)
   */
  'fetchMatchesByCompetition' : ActorMethod<[string, string], string>,
  'getPredictions' : ActorMethod<[], Array<Prediction>>,
  'isAdminAuthenticated' : ActorMethod<[string], boolean>,
  'seedInitialData' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePredictionAsAdmin' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      number,
      bigint,
      string,
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];